/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JLabel;

/**
 *
 * @author Rini
 */
public class HRD_Home extends javax.swing.JFrame {

    /**
     * Creates new form HRD_Home
     */
    public HRD_Home() {
        initComponents();
    }
     public JLabel getPop_Profile() {
        return Pop_up_profile;
    }

    public void tombolProfile(ActionListener action) {
        this.profileButton.addActionListener(action);
    }
    public void tombolLogout(ActionListener action){
        this.logoutButton.addActionListener(action);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        homeButton1 = new javax.swing.JButton();
        homeButton2 = new javax.swing.JButton();
        Pop_up_profile = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        contactButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Pemberitahuan - Home HRD1.png"))); // NOI18N
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 160, 140, 40));

        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Distribusi - Home HRD1.png"))); // NOI18N
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 100, 60));

        homeButton1.setBorderPainted(false);
        homeButton1.setContentAreaFilled(false);
        homeButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Kelola Karyawan - Home HRD1.png"))); // NOI18N
        getContentPane().add(homeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 160, 150, 50));

        homeButton2.setBorderPainted(false);
        homeButton2.setContentAreaFilled(false);
        homeButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Home - Home sales.png"))); // NOI18N
        getContentPane().add(homeButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 100, 70));

        Pop_up_profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Profil HRD.png"))); // NOI18N
        getContentPane().add(Pop_up_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, 280, 280));

        logoutButton.setBorderPainted(false);
        logoutButton.setContentAreaFilled(false);
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 260, 150, 70));

        aboutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BLANK.png"))); // NOI18N
        aboutButton.setBorderPainted(false);
        aboutButton.setContentAreaFilled(false);
        aboutButton.setDefaultCapable(false);
        aboutButton.setFocusPainted(false);
        aboutButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/About- Home Direktur_1.png"))); // NOI18N
        aboutButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/About- Home Direktur.png"))); // NOI18N
        getContentPane().add(aboutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 130, 70));

        contactButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BLANK2.png"))); // NOI18N
        contactButton.setBorderPainted(false);
        contactButton.setContentAreaFilled(false);
        contactButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Contac - Home Direktur.png"))); // NOI18N
        getContentPane().add(contactButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 160, 70));

        profileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BLANK.png"))); // NOI18N
        profileButton.setBorderPainted(false);
        profileButton.setContentAreaFilled(false);
        profileButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Profil - Home Direktur.png"))); // NOI18N
        getContentPane().add(profileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 120, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Home HRD1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRD_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRD_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRD_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRD_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRD_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pop_up_profile;
    private javax.swing.JButton aboutButton;
    private javax.swing.JButton contactButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton homeButton1;
    private javax.swing.JButton homeButton2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton profileButton;
    // End of variables declaration//GEN-END:variables
}
