/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JLabel;

/**
 *
 * @author Rini
 */
public class Sales_Home extends javax.swing.JFrame {

    /**
     * Creates new form Sales_Home
     */
    public Sales_Home() {
        initComponents();
    }

    public JLabel getPop_Profile() {
        return Pop_up_profile;
    }

    public void tombolProfile(ActionListener action) {
        this.profileButton.addActionListener(action);
    }
    public void tombolLogout(ActionListener action){
        this.logoutButton.addActionListener(action);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pop_up_profile = new javax.swing.JLabel();
        profileButton = new javax.swing.JButton();
        distribusiButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        contactButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pop_up_profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Profil - Home sales.png"))); // NOI18N
        getContentPane().add(Pop_up_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 50, 280, 280));

        profileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BLANK.png"))); // NOI18N
        profileButton.setBorderPainted(false);
        profileButton.setContentAreaFilled(false);
        profileButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Profil - Home Direktur.png"))); // NOI18N
        getContentPane().add(profileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 120, 70));

        distribusiButton.setBorderPainted(false);
        distribusiButton.setContentAreaFilled(false);
        distribusiButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Distribusi barang - Home sales.png"))); // NOI18N
        getContentPane().add(distribusiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 130, 190, 70));

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Pemberitahuan - Home sales.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 130, 160, 70));

        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Home - Home sales.png"))); // NOI18N
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, 100, 80));

        contactButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BLANK2.png"))); // NOI18N
        contactButton.setBorderPainted(false);
        contactButton.setContentAreaFilled(false);
        contactButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Contac - Home Direktur.png"))); // NOI18N
        getContentPane().add(contactButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 160, 70));

        logoutButton.setBorderPainted(false);
        logoutButton.setContentAreaFilled(false);
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 270, 130, 60));

        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BLANK.png"))); // NOI18N
        loginButton.setBorderPainted(false);
        loginButton.setContentAreaFilled(false);
        loginButton.setDefaultCapable(false);
        loginButton.setFocusPainted(false);
        loginButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/About- Home Direktur_1.png"))); // NOI18N
        loginButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/About- Home Direktur.png"))); // NOI18N
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 130, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Home sales.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pop_up_profile;
    private javax.swing.JButton contactButton;
    private javax.swing.JButton distribusiButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton profileButton;
    // End of variables declaration//GEN-END:variables
}
